# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentdb
spec:
  selector:
    matchLabels:
      app: kaddemdb 
  replicas: 1
  template:
    metadata:
      labels:
        app: kaddemdb 
    spec:
      containers:
        - name: kaddemsql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 1234
            - name: MYSQL_DATABASE
              value: kaddem

---

# Spring Boot Deployment with initContainer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentback
spec:
  selector:
    matchLabels:
      app: kaddemback
  replicas: 1
  template:
    metadata:
      labels:
        app: kaddemback
    spec:
      # initContainer to wait for MySQL to be ready
      initContainers:
        - name: init-sql-check
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 sql-service 3306; do echo "Waiting for database connection..."; sleep 5; done']
      containers:
        - name: kaddemspring
          image: hammamrabet/mohamed_mrabet_5arctic4_g2:82
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://sql-service:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: 1234
        - name: front_ctr
          image: hammamrabet/mohamed_mrabet_5arctic4_g2_front:31
          ports:
            - containerPort: 4200  # Adjust if necessary based on your frontend app's configuration

---

# Spring Boot Service
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: kaddemback
  type: NodePort
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30003

---

# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: sql-service
spec:
  selector:
    app: kaddemdb 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30002
      # Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: kaddemback
  type: NodePort
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
      nodePort: 30004  # You can specify a node port or let Kubernetes assign one automatically

