version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10

  backend:
    image: seifeddineabidi/kaddem-1.0
    container_name: backend
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "8089:8089"
    networks:
      - my-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/kaddem?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

networks:
  my-network:
    driver: bridge
