version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10

  backend:
    image: takwa2/kaddem-backend:latest
    container_name: backend_ctr
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "8089:8089"
    networks:
      - my-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/kaddem?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}

  frontend:
    image: takwa2/kaddem-frontend:latest
    container_name: frontend_ctr
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge