version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10

  backend:
    image: seifeddineabidi/kaddem-1.0:${BUILD_NUMBER}
    container_name: backend
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "8089:8089"
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "curl  http://192.168.28.144:8089 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: seifeddineabidi/seifeddineabidi_5arctic4_g2_front:${BUILD_NUMBER}
    container_name: frontend
    depends_on:
      backend_ctr:
        condition: service_healthy
    ports:
      - "4200:80"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
