version: '3.8'

services:
  backend:
    image: takwa2/kaddem-backend:latest
    networks:
      - my-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kaddem?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - db
    ports:
      - "8089:8089"

  frontend:
    image: takwa2/kaddem-frontend:latest
    depends_on:
      - backend
    networks:
      - my-network
    ports:
      - "80:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  my-network:
    driver: bridge
