pipeline {
    agent any

    environment {
            IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Git') {
            steps {
                git branch: 'TakwaSAKOUHI-5ARCTIC4-G2',
                url: 'https://github.com/Achreef01/5ARCTIC4-G2-Kaddem.git'
            }
        }

        stage('MVN CLEAN') {
            steps {
                dir('kaddem') {
                    sh 'mvn clean'
                }
            }
        }

        stage('MVN COMPILE') {
            steps {
                dir('kaddem') {
                    sh 'mvn compile'
                }
            }
        }

        stage('MVN TEST') {
            steps {
                dir('kaddem') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('MVN BUILD') {
            steps {
                dir('kaddem') {
                    sh 'mvn install'
                }
            }
        }

        stage('JaCoCo') {
            steps {
               dir('kaddem') {
                step([$class: 'JacocoPublisher',
                    execPattern: '/target/jacoco.exec',
                    classPattern: '/classes',
                    sourcePattern: '/src',
                    exclusionPattern: '/target//,/*Test,/_javassist/*'])
                }
            }
        }

        stage('Sonarqube analysis') {
            steps {
                dir('kaddem') {
                    withSonarQubeEnv('sonarqube'){
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }

    //    stage('Deploy to Nexus') {
    //        steps {
    //            dir('kaddem') {
    //                sh 'mvn deploy'
    //            }
    //        }
    //    }

    //    stage('Build backend docker image') {
    //                steps {
    //                    dir('kaddem') {
    //                        sh 'docker build -t $DOCKERHUB_USERNAME/kaddem-backend:$IMAGE_TAG .'
    //                    }
    //                }
    //    }

    //    stage('Push images to Dockerhub') {
    //            sh 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD'
    //            sh 'docker push $DOCKERHUB_USERNAME/kaddem-backend:$IMAGE_TAG'
    //    }
    }
}